
<center><h1> Basics of NumPy </h1></center>

NumPy (Numerical Python) is one of the most powerful libraries in Python for numerical computing.  
It provides:

- A high-performance **N-dimensional array object**
- Support for **vectorized operations and broadcasting**
- Tools for **linear algebra, and random numbers**

##  Importing NumPy

In [2]:
!pip install numpy

In [1]:
# Import numpy with an alias
import numpy as np

##Checking NumPy Version

In [3]:
np.__version__

'2.0.2'

##Creating Arrays
var1 = 10 var2 = 30 var3 = 40

var=(10,20,30)

Axis Dimensions

In [4]:
# Creating a 1D numpy array
arr1 = np.array([10, 20, 30, 40, 50] )
print(type(arr1))

<class 'numpy.ndarray'>


In [5]:
# Python list with mixed datatypes
list1 = [10, "20", True, 30.5]
list1

[10, '20', True, 30.5]

### ✅ Key Difference Between NumPy Array & List
- NumPy array enforces **same data type** for all elements.  
- Lists can hold **different data types**.  
- NumPy arrays allow **vectorized operations**, lists don’t.  


##Creating Arrays (Zeros, Ones)

In [6]:
# Array of zeros
arr_zero = np.zeros((2, 5), dtype=int)
print("Array of zeros:\n", arr_zero)

Array of zeros:
 [[0 0 0 0 0]
 [0 0 0 0 0]]


np.zeros() → A NumPy function that creates an array filled with zeros.

(2, 5) → Shape of the array:

2 → number of rows
5 → number of columns

Default data type (dtype) → float64 (decimal numbers) unless you specify otherwise.
- `64` → Uses **64 bits (8 bytes)** to represent each number.  
- Provides **high precision** (about 15–16 decimal digits of accuracy).
[1.20000000e+00 3.14159265e+00 1.23456790e+08]
Data type: float64
If precision is not critical, you can use:
- float32 → ~7 decimal digits, smaller memory.
- float16 → ~3 decimal digits, mainly used in deep learning (saves memory/compute).

If you want integer zeros instead of floats:
arr_zero_int = np.zeros((2, 5), dtype=int)

👉 So in short:
np.zeros((2,5)) creates a 2-row, 5-column array of float zeros.

In [7]:
# Array of ones
arr_one = np.ones((3, 4))
print("\nArray of ones:\n", arr_one)


Array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


##Type Casting in NumPy

In [8]:
# If you add a string element, NumPy will upcast all elements to string. 👉 Array of Unicode strings, each up to 21 characters long.
np.array([10, 20, "30", 40])

array(['10', '20', '30', '40'], dtype='<U21')

np.array([...]) → creates a NumPy array from the given Python list.

The list is [10, 20, "30", 40] → notice that three items are integers, but one item ("30") is a string.

🔑 NumPy Rule

A NumPy array must have all elements of the same data type.
If you mix types, NumPy will automatically upcast everything to the “most general” type that can hold all values.

👉 In this case:

Integers (10, 20, 40) → can be converted to strings.

The string "30" cannot be converted to an integer automatically.

So NumPy converts the whole array into strings.

##Array Operations vs List Operations

In [9]:
# List example
my_list = [1, 2, 3]
print(my_list * 2)

[1, 2, 3, 1, 2, 3]


## Broadcasting Operations

**Broadcasting** allows NumPy to perform arithmetic operations on arrays of **different shapes**  
without explicitly writing loops.

In [10]:
# NumPy array example
my_array = np.array([1, 2, 3])
print(my_array * 2)  # Multiplies each element by 2

[2 4 6]


In [11]:
arr_a = np.array([2, 4, 6, 8, 10])
arr_b = np.array([1, 3, 5, 7, 9])

print("Array A + B:", arr_a + arr_b)
print("Array A * 10:", arr_a * 10)

Array A + B: [ 3  7 11 15 19]
Array A * 10: [ 20  40  60  80 100]


# 🧮 Dot Product

The **dot product** is a way to multiply two vectors (or matrices).  
It combines corresponding elements and sums them up.

---

### 📐 Formula (for 1D vectors)

If  

\[
A = [a_1, a_2, a_3]
\]

\[
B = [b_1, b_2, b_3]
\]

Then  

\[
A @ B = a_1b_1 + a_2b_2 + a_3b_3
\]

---

# ✅ Dot Product in NumPy

---

### Example : 1D Vectors

```python
import numpy as np

# Two vectors
x = np.array([2, 3, 4])
y = np.array([1, 5, 2])

# Dot product
result = np.dot(x, y)
print(result)


In [12]:
arr_a = np.array([2, 4, 6, 8, 10])
arr_b = np.array([1, 3, 5, 7, 9])

# Using @ Operator (Shortcut)
print("Dot Product A·B:", arr_a @ arr_b)

Dot Product A·B: 190


##1D array from list

In [13]:
list_data = [3, 6, 9, 12]
arr_from_list = np.array(list_data)
print("Array from list:\n", arr_from_list)

# Check the type of variables
print(type(list_data))       # Type of the Python list
print(type(arr_from_list))   # Type of the NumPy array

Array from list:
 [ 3  6  9 12]
<class 'list'>
<class 'numpy.ndarray'>


# 2D array from nested list
- In NumPy, you can create **multi-dimensional arrays** (matrices) from Python nested lists.
- Each inner list represents a **row** of the 2D array.
l1 = [10, 20, 30]
l2 = [40,50,60]

In [15]:
#Example: Converting a Nested List into a 2D Array
nested_list = [[2, 4, 6],[8, 10, 12]]
# np.array(nested_list) → Converts the nested list into a 2-dimensional NumPy array.
arr_2d = np.array(nested_list)
print("\n2D Array:\n", arr_2d, "\nShape:", arr_2d.shape)



2D Array:
 [[ 2  4  6]
 [ 8 10 12]] 
Shape: (2, 3)


In [16]:
# Access element (row=0, col=1)
arr_2d[0][1]

np.int64(4)

##Random Matrices
Accessing and Slicing Arrays

In [17]:
# We can create a 1-D array using `np.array()`
sample_arr = np.array([5, 10, 15, 20, 25])

print("First element:", sample_arr[0]) # 5
print("Slice (index 1 to 3):", sample_arr[1:4]) #10,15,20
print("Last element:", sample_arr[-1]) #25

First element: 5
Slice (index 1 to 3): [10 15 20]
Last element: 25


In [18]:
# Create a 3x3 matrix of random integers between 0 and 20
# Without Seed (Random Every Time)
np.random.randint(0, 20, (3, 3))

array([[10,  1,  7],
       [ 9, 12, 14],
       [12, 12,  2]])

🎲 Controlling Random Numbers with np.random.seed()

When using NumPy's random functions, results are **random by default**.  
To make the results **reproducible**, we use **`np.random.seed()`**.

---

### ✅ What is `np.random.seed()`?

- Sets the **starting point** for NumPy's random number generator.  
- Using the same seed always produces the **same sequence of random numbers**.  
- Useful for **experiments, debugging, or sharing results**.

In [19]:
# Use random seed for reproducibility
np.random.seed(42)
np.random.randint(0, 20, (3, 3))

array([[ 6, 19, 14],
       [10,  7,  6],
       [18, 10, 10]])

##Special Matrices

In [20]:
# Zero matrix (3x4)
np.zeros((3, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [21]:
# Ones matrix (2x5)
np.ones((2, 5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# 🧾 Identity Matrix (5x5)

The **Identity Matrix** is a special kind of square matrix where:

- All **diagonal elements** = `1`
- All **non-diagonal elements** = `0`

It is usually denoted as **I**.

---

### 📐 Example: 5×5 Identity Matrix

\[
I_5 =
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 & 0 \\
0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1
\end{bmatrix}
\]

---

### ✅ In NumPy

```python
import numpy as np

# Create a 5x5 Identity Matrix
I = np.identity(5, dtype=int)
print(I)

In [22]:
# Identity matrix (5x5)
np.identity(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [23]:
# Custom value matrix (4x3 filled with 9.99)
np.full((4, 3), 9.99)

array([[9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99]])

##Mathematical Functions on Arrays

In [24]:
# Compute the sum of all elements in the array
# sample_arr = np.array([5, 10, 15, 20, 25])
# Equivalent to 5 + 10 + 15 + 20 + 25
print("Sum:", np.sum(sample_arr))

# Compute the mean (average) of the array
# Formula: sum of elements / number of elements
print("Mean:", np.mean(sample_arr))

# Compute the standard deviation
# Measures how spread out the numbers are from the mean
print("Standard Deviation:", np.std(sample_arr))

# Find the minimum value in the array
print("Min:", np.min(sample_arr))

# Find the maximum value in the array
print("Max:", np.max(sample_arr))

Sum: 75
Mean: 15.0
Standard Deviation: 7.0710678118654755
Min: 5
Max: 25


# 🎭 Boolean Masking in NumPy

Boolean masking is a technique used to **filter elements of an array** based on conditions.  
It returns a **Boolean array** (`True` / `False`) which can be used to extract specific elements.

---

### ✅ Example: Create an Array
```python
import numpy as np

arr = np.array([5, 10, 15, 20, 25, 30])
print(arr)

🎯 Step 1: Apply a Condition
mask = arr > 15
print(mask)

Output (Boolean Mask):
[False False False  True  True  True]

🎯 Step 2: Use Mask to Filter Elements
filtered = arr[mask]
print(filtered)

Output:
[20 25 30]

In [25]:
mask_arr = np.array([1, 2, 3, 4, 5])
# print("Mask < 3:", mask_arr < 3)
print("Values > 3:", mask_arr[mask_arr > 3])

Values > 3: [4 5]


##Transpose and Sorting

In [26]:
mat_example = np.array([[1, 2, 3], [4, 5, 6]])
print("Original Matrix:\n", mat_example)
print("Transpose:\n", mat_example.T)

unsorted_arr = np.array([40, 10, 30, 20, 50])
print("Unsorted:", unsorted_arr)
print("Sorted:", np.sort(unsorted_arr))

Original Matrix:
 [[1 2 3]
 [4 5 6]]
Transpose:
 [[1 4]
 [2 5]
 [3 6]]
Unsorted: [40 10 30 20 50]
Sorted: [10 20 30 40 50]


##Concatenating Arrays

In [27]:
# Create two small matrices
matA = np.array([[1, 2, 3],
                 [4, 5, 6]])

matB = np.array([[7, 8, 9],
                 [10, 11, 12]])

Row-wise Concatenation

In [28]:
np.concatenate([matA, matB], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Column-wise Concatenation

In [29]:
np.concatenate([matA, matB], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])